package com.github.catvod.demo;

import android.app.Activity;
import android.os.Bundle;

import com.github.catvod.R;
import com.github.catvod.crawler.SpiderDebug;
import com.github.catvod.spider.Bili;
import com.github.catvod.spider.Dm84;
import com.github.catvod.spider.Init;
import com.github.catvod.spider.Tpzy;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Arrays;
import java.util.HashMap;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Init.init(getApplicationContext());
    new Thread(
            () -> {
              Tpzy tpzy = new Tpzy();
              tpzy.init(
                  MainActivity.this,
                  "{\n"
                      + "  \"author\": \"zww\",\n"
                      + "  \"ua\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36\",\n"
                      + "  \"homeUrl\": \"https://www.taopianzy.com/home/index.html\",\n"
                      + "  \"dcVipFlag\": \"true\",\n"
                      + "  \"dcPlayUrl\": \"true\",\n"
                      + "  \"cateNode\": \"//ul[contains(@class,'nav-menu')]/li/a[contains(@href, 'vodtype')]\",\n"
                      + "  \"cateName\": \"/text()\",\n"
                      + "  \"cateId\": \"/@href\",\n"
                      + "  \"cateIdR\": \"/vodtype/(\\\\w+).html\",\n"
                      + "  \"cateManual\": {\n"
                      + "    \"动作片\": \"66\",\n"
                      + "    \"喜剧片\": \"67\",\n"
                      + "    \"爱情片\": \"68\",\n"
                      + "    \"科幻片\": \"69\",\n"
                      + "    \"恐怖片\": \"70\",\n"
                      + "    \"剧情片\": \"71\",\n"
                      + "    \"战争片\": \"72\",\n"
                      + "    \"悬疑片\": \"73\",\n"
                      + "    \"冒险片\": \"74\",\n"
                      + "    \"动画片\": \"75\",\n"
                      + "    \"惊悚片\": \"76\",\n"
                      + "    \"奇幻片\": \"77\",\n"
                      + "    \"纪录片\": \"78\"\n"
                      + "  },\n"
                      + "  \"homeVodNode\": \"//div[@id='homeComent']/div[@class='tableList layout']/table[@class='table table-bordered']/tbody/tr\",\n"
                      + "  \"homeVodName\": \"/td[1]/span[1]/a/text()\",\n"
                      + "  \"homeVodId\": \"/td[1]/span[1]/a/@href\",\n"
                      + "  \"homeVodIdR\": \"/home/play/\\\\w+/(\\\\w+).html\",\n"
                      + "  \"homeVodImg\": \"\",\n"
                      + "  \"homeVodImgR\": \"\",\n"
                      + "  \"homeVodMark\": \"\",\n"
                      + "  \"cateUrl\": \"https://www.taopianzy.com/home/vodlist/1/1-1/si1_&pg{catePg}_&tp{cateId}_&as63_&ye65_&lg64_&cd1.html\",\n"
                      + "  \"cateVodNode\": \"//div[@id='VRcontent']/div[@class='filter layout']/div[@class='tableList layout']/table[@class='table table-bordered']/tbody/tr\",\n"
                      + "  \"cateVodName\": \"/td[1]/span[1]/a/text()\",\n"
                      + "  \"cateVodId\": \"/td[1]/span[1]/a/@href\",\n"
                      + "  \"cateVodIdR\": \"/home/play/\\\\w+/(\\\\w+).html\",\n"
                      + "  \"cateVodImg\": \"\",\n"
                      + "  \"cateVodImgR\": \"\",\n"
                      + "  \"cateVodMark\": \"\",\n"
                      + "  \"dtUrl\": \"https://www.taopianzy.com/home/play/1/{vid}.html\",\n"
                      + "  \"dtNode\": \"//body\",\n"
                      + "  \"dtName\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/span[@class='name']/text()\",\n"
                      + "  \"dtNameR\": \"\",\n"
                      + "  \"dtImg\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='left']/img[@id='videoPoster']/@src\",\n"
                      + "  \"dtImgR\": \"\",\n"
                      + "  \"dtCate\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][4]/span[@class='two'][1]/font[@class='text']/span/text()\",\n"
                      + "  \"dtYear\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][5]/span[@class='two'][2]/text()\",\n"
                      + "  \"dtArea\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][3]/span[@class='two'][2]/font[@class='text']/span/text()\",\n"
                      + "  \"dtMark\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][5]/span[@class='two'][1]/font[2]/text()\",\n"
                      + "  \"dtDirector\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][2]/span[@class='two'][1]/font[@class='text']/span/text()\",\n"
                      + "  \"dtActor\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/div[@class='min-left']/div[@class='right']/div[@class='line'][3]/span[@class='two'][1]/font[@class='text']/span/text()\",\n"
                      + "  \"dtDesc\": \"//nav[1]/div[@id='detailsComent']/div[@class='coment layout']/div[@class='coment-min']/pre[@id='pretags']/text()\",\n"
                      + "  \"dtFromNode\": \"//nav[1]/div[@id='detailsComent']/div[@class='video-box']/div[@class='coment layout']/div[@class='playline']/div[@class='playOnline']\",\n"
                      + "  \"dtFromName\": \"/span/text()\",\n"
                      + "  \"dtFromNameR\": \"\",\n"
                      + "  \"dtUrlNode\": \"//nav[1]/div[@id='detailsComent']/div[@class='video-box']/div[@class='coment layout']/div[@id='pline0']/div[@class='playList']/table[@class='table table-bordered addrs']/tbody/tr\",\n"
                      + "  \"dtUrlSubNode\": \"\",\n"
                      + "  \"dtUrlId\": \"/td[2]/div[1]/input/@value\",\n"
                      + "  \"dtUrlIdR\": \"\",\n"
                      + "  \"dtUrlName\": \"/td[1]/span/text()\",\n"
                      + "  \"dtUrlNameR\": \"\",\n"
                      + "  \"playUrl\": \"{playUrl}\",\n"
                      + "  \"playUa\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36\",\n"
                      + "  \"playReferer\": \"https://www.taopianzy.com/home/index.html\",\n"
                      + "  \"searchUrl\": \"https://www.taopianzy.com/home/search/si1_&ky{wd}.html\",\n"
                      + "  \"scVodNode\": \"//nav[1]/div[@id='homeComent']/div[@id='VRcontent']/div[@class='tableList layout']/table[@class='table table-bordered']/tbody/tr\",\n"
                      + "  \"scVodName\": \"/td[@class='fontleft txleft']/span[@class='fontbule']/a/text()\",\n"
                      + "  \"scVodId\": \"/td[1]/span[1]/a/@href\",\n"
                      + "  \"scVodIdR\": \"/home/play/\\\\w+/(\\\\w+).html\",\n"
                      + "  \"scVodImg\": \"\",\n"
                      + "  \"scVodMark\": \"\",\n"
                      + "  \"filter\": {\n"
                      + "    \"13\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"14\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"16\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"15\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"2\": [\n"
                      + "      {\n"
                      + "        \"key\": \"cateId\",\n"
                      + "        \"name\": \"类型\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"陆剧\",\n"
                      + "            \"v\": \"13\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"日韩剧\",\n"
                      + "            \"v\": \"15\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"英美剧\",\n"
                      + "            \"v\": \"16\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"台泰剧\",\n"
                      + "            \"v\": \"14\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"港剧\",\n"
                      + "            \"v\": \"20\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"area\",\n"
                      + "        \"name\": \"地区\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"内地\",\n"
                      + "            \"v\": \"内地\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"韩国\",\n"
                      + "            \"v\": \"韩国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"香港\",\n"
                      + "            \"v\": \"香港\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"台湾\",\n"
                      + "            \"v\": \"台湾\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"美国\",\n"
                      + "            \"v\": \"美国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"英国\",\n"
                      + "            \"v\": \"英国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"巴西\",\n"
                      + "            \"v\": \"巴西\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"西班牙\",\n"
                      + "            \"v\": \"西班牙\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"泰国\",\n"
                      + "            \"v\": \"泰国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"德国\",\n"
                      + "            \"v\": \"德国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"法国\",\n"
                      + "            \"v\": \"法国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"日本\",\n"
                      + "            \"v\": \"日本\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"荷兰\",\n"
                      + "            \"v\": \"荷兰\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"3\": [\n"
                      + "      {\n"
                      + "        \"key\": \"area\",\n"
                      + "        \"name\": \"地区\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"内地\",\n"
                      + "            \"v\": \"内地\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"香港\",\n"
                      + "            \"v\": \"香港\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"台湾\",\n"
                      + "            \"v\": \"台湾\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"韩国\",\n"
                      + "            \"v\": \"韩国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"美国\",\n"
                      + "            \"v\": \"美国\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"4\": [\n"
                      + "      {\n"
                      + "        \"key\": \"area\",\n"
                      + "        \"name\": \"地区\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"国产\",\n"
                      + "            \"v\": \"国产\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"日本\",\n"
                      + "            \"v\": \"日本\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"美国\",\n"
                      + "            \"v\": \"美国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"法国\",\n"
                      + "            \"v\": \"法国\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"其他\",\n"
                      + "            \"v\": \"其他\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"20\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ],\n"
                      + "    \"21\": [\n"
                      + "      {\n"
                      + "        \"key\": \"year\",\n"
                      + "        \"name\": \"年份\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"全部\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2023\",\n"
                      + "            \"v\": \"2023\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2022\",\n"
                      + "            \"v\": \"2022\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2021\",\n"
                      + "            \"v\": \"2021\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2020\",\n"
                      + "            \"v\": \"2020\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2019\",\n"
                      + "            \"v\": \"2019\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2018\",\n"
                      + "            \"v\": \"2018\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"2017\",\n"
                      + "            \"v\": \"2017\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      },\n"
                      + "      {\n"
                      + "        \"key\": \"by\",\n"
                      + "        \"name\": \"排序\",\n"
                      + "        \"value\": [\n"
                      + "          {\n"
                      + "            \"n\": \"排序\",\n"
                      + "            \"v\": \"\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"时间\",\n"
                      + "            \"v\": \"time\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"人气\",\n"
                      + "            \"v\": \"hits\"\n"
                      + "          },\n"
                      + "          {\n"
                      + "            \"n\": \"评分\",\n"
                      + "            \"v\": \"score\"\n"
                      + "          }\n"
                      + "        ]\n"
                      + "      }\n"
                      + "    ]\n"
                      + "  }\n"
                      + "}");
              String homeContent = tpzy.homeContent(true);
              String categoryContent = tpzy.categoryContent("66", "1", false, new HashMap<>());
              String detail = tpzy.detailContent(Arrays.asList("243_71291"));
              String searcht = "";
              try {
                searcht = tpzy.searchContent("斗破", true);
              } catch (Exception e) {
                throw new RuntimeException(e);
              }
              try {
                JSONObject jsonObject = new JSONObject(homeContent);
                JSONObject category = new JSONObject(categoryContent);
                JSONObject aaa = new JSONObject(detail);
                JSONObject search = new JSONObject(searcht);
                System.out.println();
              } catch (JSONException e) {
                throw new RuntimeException(e);
              }
            })
        .start();
    }
}